### ISSUE TITLE
Getting parsing error reports from __construct

### ISSUE THREAD

**Issue by iwemuiser** [omeka/plugin-SocialBookmarking#14]
We are getting a lot of these errors. When I open the page which gave the error however, everything seems fine. We are using Omeka 2.1.2.

2014-02-21T13:05:19+01:00 ERR (3): exception 'Exception' with message 'String could not be parsed as XML' in /var/www-vb/plugins/SocialBookmarking/helpers/SocialBookmarkingFunctions.php:47
Stack trace:
#0 /var/www-vb/plugins/SocialBookmarking/helpers/SocialBookmarkingFunctions.php(47): SimpleXMLElement->__construct('')
#1 /var/www-vb/plugins/SocialBookmarking/helpers/SocialBookmarkingFunctions.php(57): social_bookmarking_get_services_xml()
#2 /var/www-vb/plugins/SocialBookmarking/helpers/SocialBookmarkingFunctions.php(87): social_bookmarking_get_services()
#3 /var/www-vb/plugins/SocialBookmarking/SocialBookmarkingPlugin.php(124): social_bookmarking_toolbar('http://www.verh...', 'Griselidis', 'Bekijk volledig...')
#4 [internal function]: SocialBookmarkingPlugin->hookPublicItemsShow(Array)
#5 /var/www-vb/application/libraries/Omeka/Plugin/Broker.php(157): call_user_func(Array, Array)
#6 /var/www-vb/application/libraries/globals.php(188): Omeka_Plugin_Broker->callHook('public_items_sh...', Array)
#7 /var/www-vb/themes/verhalenbank/items/show.php(64): fire_plugin_hook('public_items_sh...', Array)
#8 /var/www-vb/application/libraries/Omeka/View.php(117): include('/var/www-vb/the...')
#9 /var/www-vb/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/var/www-vb/the...')
#10 /var/www-vb/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('items/show.php')
#11 /var/www-vb/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('items/show.php', NULL)
#12 /var/www-vb/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#13 /var/www-vb/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#14 /var/www-vb/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#15 /var/www-vb/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#16 /var/www-vb/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#17 /var/www-vb/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#18 /var/www-vb/application/libraries/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#19 /var/www-vb/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#20 /var/www-vb/index.php(23): Omeka_Application->run()
#21 {main}

**Comment by jajm** [comment]
Same issue today.

https://cache.addthiscdn.com/services/v1/sharing.en.xml returns a 503 error with the following message:

```
An error occurred while processing your request.

Reference #30.56a1002.1566812292.47f346a 
```
